title: GroundWater Fundamentals
description: This Website aims to explan and simplify groundwater Fundamentalsfor beginners.
theme: just-the-docs

url: https://navsi08.github.io/Trial008/
baseurl: /Trial008 


aux_links:
  View on GitHub: https://github.com/NavSi08/Trial008

